dydx_full_node:
  host: 127.0.0.1 # fill in the IP address of your full node
  grpc_port: 9090
  websocket_port: 9092
use_grpc: true
use_websocket: false
stream_options:
  clob_pair_ids:  # IDs of the markets to stream
    - 0
    - 1
  subaccount_ids:
    - dydx1nzuttarf5k2j0nug5yzhr6p74t9avehn9hlh8m/0  # each subaccount id is string with format owner/number
    - dydx199tqg4wdlnu4qjlxchpd7seg454937hjrknju4/0
interval_ms: 1000 # Print book state every second
indexer_api: https://indexer.dydx.trade # Used to fetch data for unit conversions
log_stream_messages: feed.log # Log messages to this file each time main is run
print_fills: false # Whether to print fills
print_books: false # Whether to print books
print_subaccounts: true # Whether to print subaccounts
print_taker_orders: true # Whether to print taker orders