dydx_full_node:
  host: 18.177.172.207 # fill in the IP address of your full node
  grpc_port: 9090
  websocket_port: 9091
use_grpc: true
use_websocket: false
stream_options:
  clob_pair_ids:  # IDs of the markets to stream
    - 0
    - 1
  subaccount_ids:
    - dydx15u3dtsf4twdxttvy7850dkex7tcf3ps2y8wcuf/0
    - dydx14dltc2w6y3dhf0naz8luglsvjt0vhvswm2j6d0/0
interval_ms: 1000 # Print book state every second
indexer_api: http://mainnet-indexer-apne1-lb-public-2043015959.ap-northeast-1.elb.amazonaws.com
log_stream_messages: feed.log # Log messages to this file each time main is run
print_fills: true # Whether to print fills
print_taker_orders: false
print_books: false # Whether to print books
print_subaccounts: true # Whether to print subaccounts
validate_every_n_blocks: 25 # In validation mode, how many blocks between each orderbook check
